platform:
  - x64

matrix:
  fast_finish: true

skip_branch_with_pr: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: win64-msvc15-md
      HOST_ARCH_ARG: --enable-msvc
      TESTS: main
      ADD_PATH: 
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: win64-msvc16-md
      HOST_ARCH_ARG: --enable-msvc
      TESTS: main
      ADD_PATH: /mingw64/bin
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: win64-msvc15-mdd
      HOST_ARCH_ARG: --enable-msvc --enable-debug
      TESTS: none
      ADD_PATH: 
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: win64-msvc16-mdd
      HOST_ARCH_ARG: --enable-msvc --enable-debug
      TESTS: none
      ADD_PATH: 

install:
  - for /f "delims=" %%i in ('C:\msys64\usr\bin\bash -lc "if [ $APPVEYOR_REPO_BRANCH = 'master' ]; then echo 'master'; else echo $APPVEYOR_REPO_BRANCH | cut -d "/" -f 2; fi"') do set VERSION=%%i
  - IF %ARCH%==win64-msvc15-md (CALL C:\"Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat")
  - IF %ARCH%==win64-msvc16-md (CALL C:\"Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat")
  - IF %ARCH%==win64-msvc15-mdd (CALL C:\"Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat")
  - IF %ARCH%==win64-msvc16-mdd (CALL C:\"Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat")
  - C:\msys64\usr\bin\bash -lc ""

build_script:
  - C:\msys64\usr\bin\bash -lc "cd C:\projects; ln -s %APPVEYOR_PROJECT_SLUG% %APPVEYOR_PROJECT_NAME%; git clone https://github.com/coin-or/coinbrew"
  - C:\msys64\usr\bin\bash -lc "cd C:\projects; ./coinbrew/coinbrew fetch https://github.com/%APPVEYOR_REPO_NAME%@%APPVEYOR_REPO_BRANCH% --no-prompt --skip='ThirdParty/Metis ThirdParty/Mumps' --skip-update"
  - C:\msys64\usr\bin\bash -lc "cd C:\projects; export PATH=$ADD_PATH:$PATH; ./coinbrew/coinbrew build %APPVEYOR_PROJECT_NAME% --no-prompt --skip='ThirdParty/Metis ThirdParty/Mumps' --build=x86_64-w64-mingw32 $HOST_ARCH_ARG --verbosity 2 --tests $TESTS --enable-relocatable"
