---
name: Build source and run tests
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test-linux:
    name: Configure, compile and run tests on Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        build_static: [true, false]
    env:
      BUILD_STATIC: ${{ matrix.build_static }}
      DEBUG: false
      ASAN: false
      ADD_CXXFLAGS: "-fvisibility=hidden"
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}
      - name: Checkout coinbrew
        uses: actions/checkout@v2
        with:
          repository: coin-or/coinbrew
          path: coinbrew
      - name: Install required packages from package manager
        run: |
          sudo apt update -y -qq
          sudo apt install -y -qq gfortran liblapack-dev libmetis-dev libnauty2-dev
      - name: Fetch dependencies
        run: |
          bash coinbrew/.ci/install_packages.sh
          bash coinbrew/coinbrew fetch ${{ github.event.repository.name }} \
          --no-prompt --skip-update \
          --skip='ThirdParty/Metis ThirdParty/Mumps ThirdParty/Blas ThirdParty/Lapack'
      - name: Build project
        run: |
          source coinbrew/.ci/setup_environment.sh
          bash coinbrew/coinbrew build ${{ github.event.repository.name }} \
          --skip='ThirdParty/Metis ThirdParty/Mumps ThirdParty/Blas ThirdParty/Lapack' \
          "${COMMON_ARGS[@]}" "${ADD_ARGS[@]}" "${DBG_ARGS[@]}" \
          ADD_CXXFLAGS="${ADD_CXXFLAGS}" CC=${CC} CXX=${CXX}
